## SAM template to deploy the python code as a lambda function cron job
Transform: "AWS::Serverless-2016-10-31"
Description: "Lambda functions to automate various tasks in my personal infrastructure"
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: terraform-cloud-destroy
      Description: "Lambda function to run as cron job and destroy the resources created by Terraform with Terraform Cloud as backend"
      Handler: main.handler
      Runtime: python3.11
      CodeUri: src/terraform-cloud-destroy
      MemorySize: 256
      Timeout: 900
      Environment:
        Variables:
          TF_ORGANIZATION: !Ref TfCloudOrg
          TF_API_KEY: !Ref TfCloudApiKey
          TF_API_URL: !Ref TfCloudApiUrl
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 * * ? *) # Run the lambda function every day at 00:00 UTC

Parameters:
  TfCloudOrg:
    Type: String
    Description: "Terraform Cloud Organization"
  TfCloudApiKey:
    Type: String
    Description: "Terraform Cloud API Key"
  TfCloudApiUrl:
    Type: String
    Description: "Terraform Cloud API URL"
